import Head from 'next/head';
import React from 'react';

type ViewWrapperLayoutProps = {
  children: React.ReactNode;
  title: string;
};

export default function ViewWrapperLayout({
  children,
  title,
}: ViewWrapperLayoutProps) {
  return (
    <>
      <Head>
        <title>Prisma Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logopurple.svg" />
      </Head>
      <main>Content</main>
    </>
  );
}
